name: Image Bakery Pipeline

on:
  push:
    branches:
      - feature/IB
  workflow_dispatch:

jobs:

  build-image:

    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Verify Packer Installation
        run: |
          packer version

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Verify Ansible Installation
        run: |
          ansible --version

      - name: Packer Init
        working-directory: ./packer
        run: |
          packer init .

      - name: Check Packer Formatting
        working-directory: ./packer
        run: |
          packer fmt -check .

      - name: Validate Packer Template
        working-directory: ./packer
        run: |
          packer validate .

      - name: Build Golden AMI
        working-directory: ./packer
        run: |
          packer build .

      - name: Pipeline Completed
        run: |
          echo "Image Bakery Pipeline Completed Successfully"